export default {
  RAITINGS: 'RAITINGS',
  PHOTOEVENT: 'PHOTOEVENT',
  TOGGLEPHOTO: 'TOGGLEPHOTO',
  DATEEVENT: 'DATEEVENT',
  TOGGLEDATE: 'TOGGLEDATE',
  INFOEVENT: 'INFOEVENT',
  TOGGLEEVENT: 'TOGGLEEVENT',
}